version: "3"

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    networks:
      - internal
      - external

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    ports:
      - 8081:80
    networks:
      - internal
      - external

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - 8025:8025
    networks:
      - internal
      - external

volumes:
  db-data:

networks:
  internal:
    driver: bridge
  external:
